#! /bin/sh

workspaces() {
    name=1
    for monitor in $(bspc query -M); do
        bspc monitor "${monitor}" -n "$name" -d '1' '2' '3' '4' '5' '6' '7' '8' '9' '10'
        ((name++))
    done
}

workspaces

pgrep -x sxhkd > /dev/null || sxhkd &

bspc config border_width            4
bspc config window_gap              16
bspc config split_ratio             0.5
bspc config borderless_monocle      true
bspc config focus_follows_pointer   true
bspc config gapless_monocle         true
bspc config top_padding             40
bspc config bottom_padding          2
bspc config left_padding            2
bspc config right_padding           2
bspc config normal_border_color     "#689D6A"
bspc config focused_border_color    "#D79921"
bspc config active_border_color     "#FB4934"
bspc config presel_feedback_color   "#928374"
bspc config pointer_modifier        mod1
bspc config pointer_action1         move
bspc config pointer_action2         resize_side
bspc config pointer_action3         resize_corner

# [Autostart applications]

~/.fehbg
plank &
eww -c ~/.config/eww/ open bar 2>&1 > /dev/null &
xinput set-prop 10 325 1
dunst -conf ~/.config/dunst/dunstrc &
fusuma -d  2>&1 > /dev/null &
greenclip daemon &
picomj --animations --animation-for-open-window fly-in --animations --animation-for-open-window zoom -f -b &

bspc rule -a Plank border=off
bspc subscribe node_add | while read -r _
do
  xdo raise -N Plank
done &
