swipe:
  3:
    left:
      sendkey: "LEFTMETA+LEFTSHIFT+LEFT"
    right:
      sendkey: "LEFTMETA+LEFTSHIFT+RIGHT"
    up:
      sendkey: "LEFTMETA+ENTER"
    down:
      sendkey: "LEFTMETA+SPACE"
  4:
    left:
      sendkey: "LEFTALT+LEFT"
    right:
      sendkey: "LEFTALT+RIGHT"
    up:
      command: "bspc node -t 'fullscreen'"
    down:
      command: "bspc node -t 'tiled'"
pinch:
  in:
    sendkey: "LEFTCTRL+KPMINUS"
  out:
    sendkey: "LEFTCTRL+KPPLUS"
hold:
  3:
    sendkey: "LEFTMETA+SPACE"
  2:
    sendkey: "LEFTMETA+SPACE"
  4:
    sendkey: "LEFTMETA+W"
